#!/usr/bin/env node
/*
 * Our FSRS against somebody else's, on our own weights.
 *
 *   node tests/verify-oracle.js
 *
 * WHY THIS EXISTS. src/core/fsrs.js carries 46 checks and every one of them
 * was written by the same hand that wrote the code. That catches typos and
 * regressions. It cannot catch a formula transcribed wrongly from the paper,
 * because the check would carry the same wrong transcription. Only an
 * independent implementation can, and until now the most mathematically
 * load-bearing module in the project had never met one.
 *
 * ts-fsrs is that implementation, fed OUR nineteen weights so that the
 * parameters are not the variable — only the arithmetic is. It ran once, in
 * tools/gen-fsrs-oracle.js, and its answers are checked in as data. This file
 * needs no dependency at all, which is what lets CI run it: CI has the
 * repository but never the licensed export, so anything needing a build
 * protects nothing there.
 *
 * WHAT IT FOUND. Across 700 states — seven stabilities, five difficulties,
 * five elapsed intervals, four grades — the two agree to floating-point on
 * retrievability, on difficulty, and on stability for Hard, Good and Easy.
 *
 * They part on exactly one thing, and it is deliberate. On Again, ts-fsrs
 * returns the raw FSRS post-lapse stability; ours caps it at the stability the
 * card already had. fsrsNextStabilityFail explains why at length: the
 * e^((1-R)·w14) term rewards a lapse at low retrievability, and on a card
 * whose stability is already small it carries the result ABOVE where it
 * started — measured at the time, 275 of 616 reachable states came out more
 * durable after Again than before it, and 136 pushed the interval further out
 * than the card already had. A two-day card you had just failed came back in
 * five.
 *
 * So the divergence is not tolerated here, it is ASSERTED: on Again our answer
 * must equal min(theirs, prior stability), exactly. That turns an intentional
 * difference into a tested property. And because a cap that never binds is
 * indistinguishable from no cap at all, it is also asserted that it binds.
 */
'use strict';
const fs = require('fs');
const path = require('path');

let passed = 0, failed = 0;
const ok = (label, cond, detail = '') => {
  cond ? passed++ : failed++;
  console.log((cond ? '  PASS  ' : '  FAIL  ') + label + (detail ? '  → ' + detail : ''));
};
const head = t => console.log('\n── ' + t + ' ──');

const mod = {};
new Function('module', 'exports',
  fs.readFileSync(path.join(__dirname, '..', 'src', 'core', 'fsrs.js'), 'utf8'))
  .call(mod, { exports: mod }, mod);
const F = mod.FSRS;

const FIX = path.join(__dirname, 'fixtures', 'fsrs-oracle.json');
let fx = null;
try { fx = JSON.parse(fs.readFileSync(FIX, 'utf8')); } catch (e) { /* reported below */ }

head('the fixture is present, and it is about this scheduler');
ok('tests/fixtures/fsrs-oracle.json loads', !!fx,
   fx ? '' : 'regenerate with: npm i ts-fsrs && node tools/gen-fsrs-oracle.js');
if (!fx) { console.log(`\n${passed} passed, ${failed} failed`); process.exit(1); }

ok('it was generated by an implementation that is not ours',
   fx.generator && fx.generator.name === 'ts-fsrs' && !!fx.generator.version,
   `${fx.generator.name} ${fx.generator.version}`);
/* THE PIN THAT MATTERS. An oracle generated against different weights is not
   an oracle, it is a coincidence. If the weights move, the fixture is stale
   and every comparison below is meaningless — so the fingerprint is checked
   before anything is compared, and a mismatch says regenerate, not adjust. */
ok('and against the weights this scheduler actually uses',
   fx.ourFingerprint === F.paramsFingerprint(),
   `${fx.ourFingerprint} vs ${F.paramsFingerprint()}`);
ok('the weights themselves round-trip', JSON.stringify(fx.ourWeights) === JSON.stringify(F.W));
ok('and so does the decay', fx.ourDecay === F.DECAY, String(fx.ourDecay));
ok('there is a grid to compare against', fx.rows.length > 500, `${fx.rows.length} states`);
ok('and it says how precise it is', fx.outputPrecision === 1e-8, String(fx.outputPrecision));

/* THE TOLERANCE, AND WHY IT IS THIS ONE. ts-fsrs rounds every public result to
   eight decimals before returning it, so the fixture is exact to about 1e-8
   absolute and no comparison here can be tighter than its own data. It is also
   the right shape: absolute, not relative, because rounding to a fixed number
   of DECIMALS bounds the absolute error whatever the magnitude.

   1e-8 is four orders of magnitude below anything a transcribed-wrong formula
   would produce — the first draft of this file compared at 1e-9 relative and
   reported five failures that were entirely ts-fsrs's serialisation. */
const TOL = 1e-8;
const close = (a, b) => Math.abs(a - b) <= TOL;
const worst = xs => xs.reduce((m, x) => Math.max(m, x), 0);

const day = n => { const d = new Date('2026-01-01T00:00:00'); d.setDate(d.getDate() + n);
                   return d.toISOString().slice(0, 10); };

head('a card seen for the first time');
{
  const bad = fx.init.filter(([g, d, s]) =>
    !close(F.initDifficulty(g), d) || !close(F.initStability(g), s));
  ok('initial difficulty and stability agree for all four grades', bad.length === 0,
     bad.map(([g]) => 'grade ' + g).join(', '));
}

head('the forgetting curve');
{
  /* Checked against their ROUNDED value on its own terms, which is all their
     API offers. The stability columns are generated from the unrounded curve
     instead — near R = 1 the exp((1-R)·w10) - 1 term cancels the leading 1 and
     multiplies any error in R, so comparing against their rounded R would
     report a formula disagreement that does not exist: at S=40, D=1, one day
     elapsed, 4.3e-9 in R became 1.6e-5 in the stability. */
  const diffs = fx.rows.map(([S, , el, , r]) => Math.abs(F.retrievability(S, el) - r));
  ok('retrievability agrees on every state', worst(diffs) <= TOL, worst(diffs).toExponential(2));
}

head('difficulty after a review');
{
  const diffs = fx.rows.map(([S, D, el, g, , nextD]) =>
    Math.abs(F.update({ difficulty: D, stability: S, last: day(0), reps: 3 }, g, day(el)).difficulty - nextD));
  ok('agrees on every state, every grade', worst(diffs) <= TOL, worst(diffs).toExponential(2));
}

head('stability after Hard, Good or Easy');
{
  const rows = fx.rows.filter(r => r[3] !== 1);
  const diffs = rows.map(([S, D, el, g, , , nextS]) =>
    Math.abs(F.update({ difficulty: D, stability: S, last: day(0), reps: 3 }, g, day(el)).stability - nextS));
  ok('agrees on every recall state', worst(diffs) <= TOL,
     `${rows.length} states, worst ${worst(diffs).toExponential(2)}`);
}

head('stability after Again — the one deliberate divergence');
{
  const rows = fx.rows.filter(r => r[3] === 1);
  let capped = 0, wrong = [];
  for (const [S, D, el, , , , theirs] of rows) {
    const ours = F.update({ difficulty: D, stability: S, last: day(0), reps: 3 }, 1, day(el)).stability;
    const want = Math.min(theirs, S);
    if (theirs > S) capped++;
    if (!close(ours, want)) wrong.push(`S=${S} D=${D} el=${el}: ${ours} vs ${want}`);
  }
  ok('ours is exactly min(theirs, the stability it already had)', wrong.length === 0,
     wrong.slice(0, 2).join(' | ') || `${rows.length} lapse states`);
  /* A cap that never binds is indistinguishable from no cap. */
  ok('and the cap actually binds — it is not decoration', capped > 0,
     `${capped} of ${rows.length} lapses would otherwise have grown`);
  ok('forgetting never makes a card more durable, on any state in the grid',
     rows.every(([S, D, el]) =>
       F.update({ difficulty: D, stability: S, last: day(0), reps: 3 }, 1, day(el)).stability <= S + 1e-12));
}

head('and the interval that comes out the far side');
{
  /* Interval is policy, not model: ours is ceil(stability), which at the 90%
     target IS the stability by definition. Asserted against our own rule
     rather than against ts-fsrs, whose next_interval solves the curve and
     rounds differently — comparing them would be measuring a disagreement
     nobody has. */
  const bad = fx.rows.filter(([S, D, el, g]) => {
    const u = F.update({ difficulty: D, stability: S, last: day(0), reps: 3 }, g, day(el));
    return u.ivl !== Math.max(1, Math.ceil(u.stability));
  });
  ok('is the stability, rounded up, and never below one day', bad.length === 0, String(bad.length));
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
