window.FACTS = [
["Diagnostic thresholds","Normal <120/80. Elevated 120–129 and <80. Stage 1 130–139 or 80–89. Stage 2 ≥140 or ≥90. Take the higher stage of the two numbers."],
["When stage 1 gets a drug","Only with established ASCVD, diabetes, CKD, or 10-year ASCVD risk ≥10%. Otherwise lifestyle and reassess in 3–6 months."],
["When to start two drugs","Stage 2, or BP more than 20/10 above target. Two agents from different classes, preferably as a single-pill combination."],
["Out-of-office equivalents","Office 130/80 ≈ home 130/80 ≈ daytime ambulatory 130/80 ≈ 24-hour 125/75 ≈ night 110/65."],
["First-line classes","Thiazide-type diuretic, ACE inhibitor, ARB, dihydropyridine calcium blocker. Beta-blockers are not first-line without a compelling indication."],
["Black patients, no HF or CKD","Start a thiazide or a calcium blocker, not an ACE inhibitor or ARB (ALLHAT). Add RAS blockade for albuminuric CKD regardless."],
["Chlorthalidone over HCTZ","Longer half-life, greater 24-hour and nocturnal effect, the outcome data (ALLHAT, SHEP). Watch sodium and potassium."],
["SPRINT","SBP <120 by unattended automated office BP cut cardiovascular events and death in high-risk non-diabetics. More AKI, syncope, electrolyte problems. Unattended readings run roughly 5–10 mm Hg below routine office values."],
["Resistant hypertension","Above goal on three drugs at optimal dose including a diuretic, or controlled needing four. Exclude mistechnique, non-adherence, white coat effect and interfering drugs first."],
["Fourth agent","Spironolactone (PATHWAY-2) beat bisoprolol and doxazosin. Check potassium and creatinine at 1–2 weeks."],
["Screen for primary aldosteronism","Resistant hypertension, spontaneous or diuretic-induced hypokalaemia, adrenal incidentaloma, early-onset hypertension, stroke before 40, family history of early hypertension. Aldosterone-to-renin ratio."],
["Drugs that spoil the ARR","Spironolactone and eplerenone (stop 4–6 weeks). Beta-blockers and clonidine raise it falsely; ACEi, ARB and diuretics lower it. Calcium blockers and alpha-blockers are the safest cover."],
["Phaeochromocytoma","Plasma free metanephrines or 24-hour fractionated urine metanephrines. Alpha-blockade first (phenoxybenzamine or doxazosin), beta-blockade only after — unopposed alpha causes a hypertensive crisis."],
["Renal artery disease","Fibromuscular dysplasia: young women, string-of-beads mid-to-distal, responds to angioplasty. Atherosclerotic: older, ostial, CORAL and ASTRAL showed no benefit from stenting over medical therapy."],
["Bilateral renal artery stenosis","A rise in creatinine >30% or acute kidney injury after starting an ACE inhibitor or ARB is the classic clue."],
["Emergency versus urgency","Acute target-organ damage defines the emergency — encephalopathy, ICH, papilloedema, ACS, pulmonary oedema, dissection, eclampsia, acute kidney injury, microangiopathic haemolysis. A high number alone is urgency: oral drugs, no ICU."],
["The 25% rule","In most emergencies cut MAP by no more than 25% in the first hour, then to about 160/100 over 2–6 hours, then normal over 24–48 hours. Overshoot causes watershed infarction."],
["The exceptions to the 25% rule","Aortic dissection: SBP 100–120 and heart rate <60 within 20 minutes — beta-blocker (esmolol, labetalol) before any vasodilator, or reflex tachycardia widens the tear. Also different targets in ischaemic stroke thrombolysis (<185/110) and eclampsia."],
["Pregnancy","Labetalol, nifedipine, methyldopa. ACE inhibitors, ARBs, aldosterone antagonists and direct renin inhibitors are contraindicated — fetopathy in the second and third trimesters. Magnesium for eclampsia, delivery is the cure."],
["Coarctation","Upper-limb hypertension, radiofemoral delay, a systolic murmur over the back, rib notching. Check both arms and a leg in any young hypertensive."],
["Pressor drugs to ask about","NSAIDs, combined oral contraceptives, decongestants, sympathomimetics, glucocorticoids, ciclosporin and tacrolimus, erythropoietin, VEGF inhibitors, licorice, alcohol, amphetamines and cocaine, SNRIs."],
["White coat and masked","White coat: office high, out-of-office normal — confirm before treating. Masked: office normal, out-of-office high — carries the risk of sustained hypertension and is missed unless you look."],
["Albuminuria","An ACE inhibitor or ARB is preferred in CKD with albuminuria, for the kidney as much as for the pressure. Never combine an ACE inhibitor with an ARB."],
["Measurement technique","Seated five minutes, back supported, feet flat, arm at heart level, correct cuff size (bladder 80% of arm circumference), no talking, no caffeine or smoking for 30 minutes, bare arm. Average two or more readings on two or more occasions."]
];
