/* ═══════════════════════════════════════════════════════════════════════════
   ocr.js — reading a scanned page: a picture of text with no text layer.

   pdf.js reads a PDF's text layer; a scan has none, so until now its pages
   were named to the user ("no readable text — scanned?") and left out of
   every section. This reads them with Tesseract (tesseract.js 5.1.1, its
   LSTM core, English), on the device, and hands the result on in the SAME
   SHAPE pdf.js gives text in — items with a transform and a width — so
   pdf.js's linesOf() turns them into lines and chunk.js never knows the
   difference: headings by size, paragraphs, lists and tables all work as
   they do for real text.

   LOADED ONLY WHEN NEEDED, AND CHECKED. Nothing is fetched until a PDF has
   a page with no text. Then four files come from jsDelivr, each pinned to a
   version and fetched with a subresource-integrity hash: the library, its
   worker, its core (the SIMD build where the browser has SIMD) and the
   English model (the 2.9 MB "best_int" one). The worker runs from one
   blob: URL holding the checked core and the checked worker, and the
   model's bytes are handed to Tesseract directly, so nothing runs or is
   read that was not checked. About 7 MB, once; the service worker keeps them for offline use.

   The pure part — ocrItems() — is tested in bare Node
   (tests/verify-memorizer-chunk-pure.js); the rest end to end, on a scanned
   page generated by the browser suite.
   ═══════════════════════════════════════════════════════════════════════════ */
(function (root) {
'use strict';

var NPM = 'https://cdn.jsdelivr.net/npm/';
var TESS = {
  lib: { url: NPM + 'tesseract.js@5.1.1/dist/tesseract.min.js', sri: 'sha384-GJqSu7vueQ9qN0E9yLPb3Wtpd7OrgK8KmYzC8T1IysG1bcvxvIO4qtYR/D3A991F' },
  worker: { url: NPM + 'tesseract.js@5.1.1/dist/worker.min.js', sri: 'sha384-zxn+VqofFzXpH99dUb3fa4ywoSBQJPy6/6oEaJHPlblZXr53a0g1Jl6720vgSzB7' },
  coreSimd: { url: NPM + 'tesseract.js-core@5.1.1/tesseract-core-simd-lstm.wasm.js', sri: 'sha384-YM1G+zaWYy9VSRP2C101LCgzh7n3Hqb6OEm9qDoZYgCADsni3nnECskC3WialQB7' },
  core: { url: NPM + 'tesseract.js-core@5.1.1/tesseract-core-lstm.wasm.js', sri: 'sha384-EKWY5JDwphQoyxhvYU7eaCcyQ0EdV6fZK3L2vzfZcv2ichRdNd6pSnyWPNv6fMuR' },
  eng: { url: NPM + '@tesseract.js-data/eng@1.0.0/4.0.0_best_int/eng.traineddata.gz', sri: 'sha384-JI+fraGAoc5GBGIliuqzHRnP1nJyrukg5ggNSBv/TO+YOVj+6Te6XXQOx7ia10xq' },
};

/* Pages are drawn at this many device pixels per PDF unit before reading:
   2 makes 11 pt body text about 30 px tall, which Tesseract reads well. */
var SCALE = 2;
/* A word Tesseract is less sure of than this (0..100) is left out: on a
   scan it is a smudge, a rule or a bit of a figure read as letters. */
var MIN_CONFIDENCE = 30;
/* createWorker() never settles when Tesseract fails to initialise — it
   swallows the error (the mutation run against the unfixed worker hung the
   whole import on "Downloading…"). A start that takes longer than this is
   a failure, and the scanned pages are named as unread instead. */
var START_TIMEOUT_MS = 90000;

/* ── pure: Tesseract's lines → pdf.js-shaped text items ──────────────────
   blocks: Tesseract's blocks → paragraphs → lines → words, each with a
   bbox in canvas pixels, y DOWN. pdf.js items have y UP, in PDF units, at
   the baseline, with the font size in the transform. Every word of a line
   gets the line's baseline and the line's size (its row height), so a line
   stays one line in linesOf() and headings still stand out by size; the
   words keep their own x and width, so linesOf() still puts spaces and
   table cells where the gaps are. */
function ocrItems(blocks, scale, pageHeight) {
  var out = [], all = [];
  (blocks || []).forEach(function (b) {
    (b.paragraphs || []).forEach(function (p) {
      (p.lines || []).forEach(function (l) {
        var lb = l.bbox || {};
        var rowH = l.rowAttributes && l.rowAttributes.row_height > 0 ? l.rowAttributes.row_height : (lb.y1 - lb.y0);
        var size = rowH / scale;
        var base = l.baseline && isFinite(l.baseline.y0) && isFinite(l.baseline.y1) ? (l.baseline.y0 + l.baseline.y1) / 2 : lb.y1;
        var y = pageHeight - base / scale;
        /* Each word carries its own trailing space, as a pdf.js run of real
           text does. Without it, linesOf() sees a line whose every gap is a
           word gap, reads it as letter-spaced (a tracked heading), sets its
           space threshold above all of them and joins every word — measured:
           "Preloadisthestretchonventricular…". */
        (l.words || []).forEach(function (w) {
          var t = String(w.text || '').trim();
          if (t) all.push({ confidence: w.confidence });
          if (!t || !(w.confidence >= MIN_CONFIDENCE) || !w.bbox) return;
          out.push({ str: t + ' ', width: (w.bbox.x1 - w.bbox.x0) / scale, transform: [size, 0, 0, size, w.bbox.x0 / scale, y] });
        });
      });
    });
  });
  /* how sure it was of the page, words kept or not (study.js), carried on
     the list so the page's reader can file it */
  var S = root.MemStudy || (typeof require === 'function' ? require('./study.js') : null);
  out.confidence = S ? S.pageConfidence(all, MIN_CONFIDENCE) : null;
  return out;
}

/* ── the engine, loaded once ─────────────────────────────────────────────── */
/* wasm-feature-detect's SIMD probe: a module using one SIMD instruction. */
function hasSimd() {
  try {
    return WebAssembly.validate(new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 123, 3, 2, 1, 0, 10, 10, 1, 8, 0, 65, 0, 253, 15, 253, 98, 11]));
  } catch (_) { return false; }
}
/* A checked download, as bytes. Read through FileReader rather than
   Response.arrayBuffer(): the iPadOS floor scan cannot tell that from
   Blob.arrayBuffer() (Safari 14), and FileReader works on every Safari
   this app supports. */
function bytesOf(blob) {
  return new Promise(function (resolve, reject) {
    var fr = new FileReader();
    fr.onload = function () { resolve(fr.result); };
    fr.onerror = function () { reject(fr.error || new Error('could not read a download')); };
    fr.readAsArrayBuffer(blob);
  });
}
function checked(f) {
  return fetch(f.url, { integrity: f.sri, mode: 'cors' }).then(function (r) {
    if (!r.ok) throw new Error(f.url + ' ' + r.status);
    return r.blob();
  }).then(bytesOf);
}
function blobUrl(buf, type) { return URL.createObjectURL(new Blob([buf], { type: type })); }

/* tesseract.js 5.1.1's worker loads a language given as { code, data } by
   its code, then INITIALISES it by its data — `l.data` where `l.code` is
   meant (src/worker-script/index.js, initialize) — so Tesseract is asked
   for a language named "31,139,8,…" and fails, and createWorker() swallows
   the failure and never settles. Measured: the first run hung here. The
   worker's checked source is corrected in that one place before it runs,
   by the patch chain's rule: the anchor must match exactly once, or this
   throws rather than guess. */
var WORKER_FIX = { find: 'return"string"==typeof t?t:t.data})).join("+")', replace: 'return"string"==typeof t?t:t.code})).join("+")' };
function fixWorker(text) {
  var n = String(text).split(WORKER_FIX.find).length - 1;
  if (n !== 1) throw new Error('the text reader\'s worker has changed (anchor found ' + n + ' times)');
  return String(text).replace(WORKER_FIX.find, WORKER_FIX.replace);
}

var starting = null;
function engine(onStatus) {
  if (starting) return starting;
  var core = hasSimd() ? TESS.coreSimd : TESS.core;
  if (onStatus) onStatus('Downloading the text reader for scanned pages (about 7 MB, once)…');
  starting = root.MemPdf.loadScript(TESS.lib.url, TESS.lib.sri, 'could not load the text reader for scanned pages — are you offline?')
    .then(function () { return Promise.all([checked(TESS.worker), checked(core), checked(TESS.eng)]); })
    .then(function (r) {
      var T = root.Tesseract;
      if (!T) throw new Error('the text reader loaded but did not start');
      /* ONE blob: the core, then the worker. A worker started from a blob
         cannot importScripts() a second blob when the page was opened as a
         local file (its origin is opaque) — measured: the first version
         passed the core as its own blob: URL and Chromium refused it. The
         worker only imports its core when TesseractCore is not yet defined,
         and here the core has already defined it, so nothing is imported. */
      var started = T.createWorker([{ code: 'eng', data: new Uint8Array(r[2]) }], 1, {
        workerPath: blobUrl(new Blob([r[1], '\n;\n', fixWorker(new TextDecoder().decode(r[0]))]), 'text/javascript'), workerBlobURL: false,
        cacheMethod: 'none', gzip: true,
      });
      return Promise.race([started, new Promise(function (_, reject) {
        setTimeout(function () { reject(new Error('the text reader did not start')); }, START_TIMEOUT_MS);
      })]);
    });
  starting.catch(function () { starting = null; });
  return starting;
}

/* Read one pdf.js page: draw it, recognise it, return pdf.js-shaped items. */
function readPage(page, onStatus) {
  return engine(onStatus).then(function (worker) {
    var vp = page.getViewport({ scale: SCALE });
    var canvas = document.createElement('canvas');
    canvas.width = Math.ceil(vp.width); canvas.height = Math.ceil(vp.height);
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#FFFFFF'; ctx.fillRect(0, 0, canvas.width, canvas.height);
    return page.render({ canvasContext: ctx, viewport: vp }).promise.then(function () {
      return worker.recognize(canvas, {}, { text: false, blocks: true, hocr: false, tsv: false });
    }).then(function (res) {
      return ocrItems(res.data.blocks, SCALE, page.getViewport({ scale: 1 }).height);
    });
  });
}

/* A photo of a page: drawn to a canvas no wider than PHOTO_MAX_WIDTH (big
   phone photos gain nothing past it and take far longer), recognised, and
   handed back as items in the photo's own pixels — one pixel as one unit,
   which is all linesOf() and chunk.js need, since they compare sizes and
   gaps with each other, never with a real point size. */
var PHOTO_MAX_WIDTH = 2400;
function imageCanvas(blob) {
  return new Promise(function (resolve, reject) {
    var url = URL.createObjectURL(blob), img = new Image();
    img.onload = function () {
      var k = Math.min(1, PHOTO_MAX_WIDTH / img.naturalWidth);
      var c = document.createElement('canvas');
      c.width = Math.round(img.naturalWidth * k); c.height = Math.round(img.naturalHeight * k);
      var ctx = c.getContext('2d');
      ctx.fillStyle = '#FFFFFF'; ctx.fillRect(0, 0, c.width, c.height);
      ctx.drawImage(img, 0, 0, c.width, c.height);
      URL.revokeObjectURL(url);
      resolve(c);
    };
    img.onerror = function () { URL.revokeObjectURL(url); reject(new Error('that image could not be opened')); };
    img.src = url;
  });
}
function readImage(blob, onStatus) {
  var canvas;
  return imageCanvas(blob).then(function (c) { canvas = c; return engine(onStatus); }).then(function (worker) {
    return worker.recognize(canvas, {}, { text: false, blocks: true, hocr: false, tsv: false });
  }).then(function (res) {
    return { items: ocrItems(res.data.blocks, 1, canvas.height), height: canvas.height };
  });
}

root.MemOcr = { readImage: readImage, PHOTO_MAX_WIDTH: PHOTO_MAX_WIDTH, START_TIMEOUT_MS: START_TIMEOUT_MS, WORKER_FIX: WORKER_FIX, fixWorker: fixWorker, TESS: TESS, SCALE: SCALE, MIN_CONFIDENCE: MIN_CONFIDENCE, ocrItems: ocrItems, readPage: readPage, hasSimd: hasSimd };
if (typeof module !== 'undefined' && module.exports) module.exports = root.MemOcr;
})(typeof window !== 'undefined' ? window : this);
